### ISSUE TITLE
does not work on windows server 2012

### ISSUE THREAD

**Issue by vnaum** [glasnt/wail2ban#1]
workaround is very simple:
`
diff --git a/wail2ban.ps1 b/wail2ban.ps1
index 0cb9342..1bdd4f0 100755
--- a/wail2ban.ps1
+++ b/wail2ban.ps1
@@ -68,6 +68,7 @@ $WhiteList = @()
 #You can overload the BlockType here for 2003, if you feel like having fun.
 $OSVersion = invoke-expression "wmic os get Caption /value"
 if ($OSVersion -match "2008") { $BLOCK_TYPE = "NETSH" }
+if ($OSVersion -match "2012") { $BLOCK_TYPE = "NETSH" }

 #Grep configuration file
 switch -regex -file $ConfigFile {
`

**Comment by glasnt** [comment]
Thanks for the patch! I've just applied it now ✨
