### ISSUE TITLE
wail2ban is not scanning IIS's logs files

### ISSUE THREAD

**Issue by Magissia** [glasnt/wail2ban#10]
fail2ban can be configured to search in any log files, wail2ban only check Window's events store and does not bother to check any on file logs, we should be able to add regex and files to scan for addition data to make bans using the same syntax fail2ban uses for compatibility.

wail2ban could load all configuration files in a subfolder with additional regex and file paths to keep an eye on.

**Comment by glasnt** [comment]
Thank you for this bug report. This repo is [No Maintenance Intended](http://unmaintained.tech/). This issue will be closed.
