### ISSUE TITLE
continue on issues#5

### ISSUE THREAD

**Issue by maco1717** [glasnt/wail2ban#6]
continuing here https://github.com/glasnt/wail2ban/issues/5 ...
So I've downloaded the lateste release and still have the same issues, what I've noticed is that on the logs themselves I get and empty souce network address field, I'm trying this on a local PC so the IPs should be all "private" LAN IPs I dont know if that would have any effect also I've seen some people saying this is related to the encryption and the type of connections there was a few way of solving this for 2008 but havent found anything for 2012 R2 dont know if anyone will have seen this and have a solution or any guidance on where to start looking in to this?
Regards and Thanks.

**Comment by glasnt** [comment]
Hi, as I mentioned in the other PR (https://github.com/glasnt/wail2ban/pull/4#issuecomment-266885463) I have no way to test or debug any of these issues as I don't have access to any Windows server systems. 

In addition, this repo is marked "No maintenance intended". 

I'm sorry I'm unable to help you.

**Comment by maco1717** [comment]
Hi, I appreciate that is marked as no maintenance needed. I see what I can do to sort my issues.

Kind regards and thanks
