### ISSUE TITLE
where is the BannnedIPLog.ini file

### ISSUE THREAD

**Issue by maco1717** [glasnt/wail2ban#7]
Hi,

I was wondering is this had been implemented?

Kind regards and thanks.
\Marco

**Comment by glasnt** [comment]
Hi @maco1717 

This file is generated at runtime and stores state. Take a look through the code for instances of the [$BannedIPLog](https://github.com/glasnt/wail2ban/blob/master/wail2ban.ps1#L45) variable, which is the filename to store this data.
